### ISSUE TITLE
Unable to install properly HSDatalog V1 on windows 11 and WSL Ubuntu

### ISSUE THREAD

**Issue by ml13390** [STMicroelectronics/fp-sns-datalog1#1]
I start a project with the STEVAL-STWINKT1B and I followed the process to install HSDatalog on Windows 11 and WSL Ubuntu. Unfortunately, neither works as expected and I'm not able to run the example python application. Also, the hsdatalo_GUI.py is not present in the example folder.
I tried to use the HSDatalogger V2. The install worked properly on windows but it seems that this version is not able to work with the STWINKT1B board....

**Comment by pradolis** [comment]
To help you solving the issue I have a couple of questions:
- Can you share the installer log error? Is the same for both Windows and Linux machines?
- When you talk about HSDatalog and HSDatalogger V2 are you referring to FP-SNS-DATALOG1 and FP-SNS-DATALOG2?

hsdatalog_GUI scripts works only with the examples available in FP-SNS-DATALOG2. It is the unique script inside the Python SDK that is not compatible with FP-SNS-DATALOG1, that's why it has not been released inside the package.

Just for your knowledge: we are still working on FP-SNS-DATALOG2 and we'll have a new release by October adding also the support for STEVAL-STWINKT1B there. 
So, in a couple of months, hsdatalog_GUI will run also with STWIN kit. As for now, you can still use the STWIN with FP-SNS-DATALOG1 acquiring data via SD card or via USB through the C++ CLI example.

Lets dig in the Python installer problem to let you use the Python CLI and utilities

**Comment by ml13390** [comment]
Thank you for your quick reply.
here is a fresh install done on another PC. I did on a notebook 

HSDPython_SDK install Notebook - Windows 10
Preliminary :
Anaconda
VSCode
Git

Repo clone with the commande "git clone [https://github.com/STMicroelectronics/fp-sns-datalog1"](https://github.com/STMicroelectronics/fp-sns-datalog1%22) from the Home folder Notebook creation in fp-sns-datalog1/Utilities/HSDPython_SDK

Next is the process described in README.md

Install the SDK
by launching ./HSDPython_SDK_install.bat. The script will install all the wheels with the required dependencies and will create and enable a virtual environment.

No proxy > I run the script step by step

Section 1: st_pnpl
===========================================
installing st_pnpl...
===========================================
 
%pip install st_pnpl\dist\st_pnpl-1.2.0-py3-none-any.whl
Processing c:\users\marcl\fp-sns-datalog1\utilities\hsdpython_sdk\st_pnpl\dist\st_pnpl-1.2.0-py3-none-any.whl
Installing collected packages: st-pnpl
Successfully installed st-pnpl-1.2.0
Note: you may need to restart the kernel to use updated packages.


Section 2: st_dtdl_gui
===========================================
installing st_dtdl_gui...
===========================================

%
%pip install st_dtdl_gui\dist\st_dtdl_gui-1.2.0-py3-none-any.whl
Processing c:\users\marcl\fp-sns-datalog1\utilities\hsdpython_sdk\st_dtdl_gui\dist\st_dtdl_gui-1.2.0-py3-none-any.whl
Note: you may need to restart the kernel to use updated packages.
WARNING: Requirement 'st_dtdl_gui\\dist\\st_dtdl_gui-1.2.0-py3-none-any.whl' looks like a filename, but the file does not exist
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\marcl\\fp-sns-datalog1\\Utilities\\HSDPython_SDK\\st_dtdl_gui\\dist\\st_dtdl_gui-1.2.0-py3-none-any.whl'

Section 3: st_hsdatalog (GUI version)
===========================================
installing st_hsdatalog (GUI version)...
===========================================

%pip install st_hsdatalog\dist\GUI\st_hsdatalog-2.2.0-py3-none-any.whl
Processing c:\users\marcl\fp-sns-datalog1\utilities\hsdpython_sdk\st_hsdatalog\dist\gui\st_hsdatalog-2.2.0-py3-none-any.whlNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: st-pnpl in c:\users\marcl\anaconda3\lib\site-packages (from st-hsdatalog==2.2.0) (1.2.0)
INFO: pip is looking at multiple versions of st-hsdatalog to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement st-dtdl-gui (from st-hsdatalog) (from versions: none)
ERROR: No matching distribution found for st-dtdl-gui


Section 4: asciimatics needed from hsdatalog_cli.py example script
===========================================
installing asciimatics...
===========================================

%pip install asciimatics
Collecting asciimatics
  Downloading asciimatics-1.14.0-py2.py3-none-any.whl (144 kB)
                                              0.0/144.5 kB ? eta -:--:--
     ----------------                        61.4/144.5 kB 1.7 MB/s eta 0:00:01
     -----------------------------          112.6/144.5 kB 3.3 MB/s eta 0:00:01
     -------------------------------------- 144.5/144.5 kB 1.7 MB/s eta 0:00:00
Collecting pyfiglet>=0.7.2 (from asciimatics)
  Downloading pyfiglet-0.8.post1-py2.py3-none-any.whl (865 kB)
                                              0.0/865.8 kB ? eta -:--:--
     -----------                            256.0/865.8 kB 7.9 MB/s eta 0:00:01
     ------------                           286.7/865.8 kB 3.5 MB/s eta 0:00:01
     ----------------                       368.6/865.8 kB 3.9 MB/s eta 0:00:01
     ---------------------                  481.3/865.8 kB 2.8 MB/s eta 0:00:01
     -------------------------------------  860.2/865.8 kB 4.2 MB/s eta 0:00:01
     -------------------------------------- 865.8/865.8 kB 3.9 MB/s eta 0:00:00
Requirement already satisfied: Pillow>=2.7.0 in c:\users\marcl\anaconda3\lib\site-packages (from asciimatics) (9.4.0)
Requirement already satisfied: wcwidth in c:\users\marcl\anaconda3\lib\site-packages (from asciimatics) (0.2.5)
Requirement already satisfied: future in c:\users\marcl\anaconda3\lib\site-packages (from asciimatics) (0.18.3)
Requirement already satisfied: pywin32 in c:\users\marcl\anaconda3\lib\site-packages (from asciimatics) (305.1)
Installing collected packages: pyfiglet, asciimatics
Successfully installed asciimatics-1.14.0 pyfiglet-0.8.post1
Note: you may need to restart the kernel to use updated packages.
​

**Comment by ml13390** [comment]
I tried the install_noGui and it works fine with the examples.
So, I'm going to wait a bit for the update of the HSDataLog V2.
With the noGui script, it works properly on Windows. I didn't try it on linux but I don't see why it wouldn't work.
I just suggest to update the readme file in the HSDatalog V1 to avoid a confusion regarding the GUI since it is not available for this version.
Thank you
