### ISSUE TITLE
"st_dtdl_gui" folder is missing in HSDPython_SDK

### ISSUE THREAD

**Issue by adrien-cleris** [STMicroelectronics/fp-sns-datalog1#2]
Inside ".\Utilities\HSDPython_SDK", "st_dtdl_gui" folder is missing.

**Comment by pradolis** [comment]
Hello @adrien-cleris ,
st_dtdl_gui is used by live plot Python application that are not compatible with DATALOG1 firmwares.
hsdatalog_gui.py can't work with DATALOG1.
Instead, all other scripts are working as expected, and they are not dependent on st_dtdl_gui package.
So, we will not add this package inside FP-SNS-DATALOG1

The boards and firmware that can are fully compatible with also the hsdatalog_gui script are available in [FP-SNS-DATALOG2](https://github.com/STMicroelectronics/fp-sns-datalog2).
For your information, we are working to add STWIN support also in FP-SNS-DATALOG2
