### ISSUE TITLE
Support for steval proteus board

### ISSUE THREAD

**Issue by LucaMaurelliC** [STMicroelectronics/fp-sns-datalog1#4]
Am I missing something for using the latest version of datalog1 for the steval proteus board? There is no stated support for it but in its released application there is an old HSD utility related to the datalog1 as far as I know. Should I be aware of something? Should I instead use the datalog2?

I'm investing these days the Python SDK in order to connect at least two devices together and switch between them somehow beforing starting the acquisition. In other words, I'm interested in orchestrating which device to control considering that they are already connected to the host.

**Comment by pradolis** [comment]
Hello @LucaMaurelliC
PROTEUS board is not supported nor in FP-SNS-DATALOG1 neither in FP-SNS-DATALOG2.
A Function Pack specifically designed for PROTEUS has been release a couple of weeks ago: FP-SNS-DATAPRO1 ([link](https://www.st.com/en/embedded-software/fp-sns-datapro1.html)).
The responsible for PROTEUS support included in this new package a subset of the HSD PythonSDK that can be used for PROTEUS acquisition and data processing.

All the DATALOG software I'm citing here are not meant to handle more devices at the same time on the same host.
This is a new feature we can investigate for FP-SNS-DATALOG2 and for further DATALOG examples we'll publish during the year.

Best regards
Simone

**Comment by LucaMaurelliC** [comment]
Do you mind elaborating more on how both FP-SNS-DATALOG1 and FP-SNS-DATALOG2 do not support the proteus board?
Also, what is the right repository where I can browse the datalog which supports proteus? I'm asking because from the release notes of the source code of one proteus application, the link referred to this repository, i.e. FP-SNS-DATALOG1.

**Comment by pradolis** [comment]
Hello @LucaMaurelliC 
Since you got a separate discussion with some other colleagues from ST regarding the support for PROTEUS board, I'm closing the issue as solved.
Please reopen it if you need some further support on the topic.

Best regards
Simone
