### ISSUE TITLE
json.hpp causing error while executing main.cpp for cli_example

### ISSUE THREAD

**Issue by Starkeus** [STMicroelectronics/fp-sns-datalog1#5]
Hi,
I am compiling some changes I made for the main.cpp of the cli_example app and when I do so, I am getting several errors from json.hpp. I am making these changes for the STWINKT1B board.

What was the compilation procedure used on main.cpp to make the cli_example.exe? Thanks.

**Comment by pradolis** [comment]
Hello @Starkeus 
_cli_example_ folder contains the _CMakeLists_ file that already links the libraries used by the executable. We are using _cmake_.
So, to recompile the project you should be able to modify the main.cpp and recompile the application (i.e.: execute _cmake CMakeLists.txt && make_ command).

If the above procedure doesn't work, can you share the error you get?


Best regards
Simone

**Comment by pradolis** [comment]
Hello @Starkeus 
No news from your side, so I guess the issue can be closed.

Feel free to contact us again if the issue persists on your side.
Best regards
